name: Say hello world workflow

on: 
  push:  

jobs: 
  say-hello:
    runs-on: ubuntu-latest 
    steps: 
     - name: checkout actions
       uses: actions/checkout@v2 
     - name: say-hello 
       run: mkdir abc && cd abc && touch test.txt  
        
