name: Say hello world workflow

on:
  push:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repo
       uses: actions/checkout@v3
       with:
         token: ${{ secrets.PAT_TOKEN }}
         fetch-depth: 0

     - name: Commit & Push changes
       run: |
         git config user.name "programmingwithrakib"
         git config user.email "programmingwithrakib@gmail.com"
      
        
