name: Server Deploy
on: 
  push:
      branches:
        - main 

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Connect & Pull On Server
        uses: appleboy/ssh-action@v0.1.10
        with: 
          host: 51.79.146.178 
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: | 
            script: |
              cd ~
              if [ ! -d "git-test" ]; then
                git clone https://github.com/programmingwithrakib/git-test.git
              fi
              cd git-test
              git checkout main
              git pull origin main 

